const articles = [
  { slug:'city-sounds', title:'الرجل الذي كان يجمع أصوات المدينة', category:'قصص قصيرة', categorySlug:'short-stories', date:'الأحد، ٢٧ سبتمبر ٢٠٢٦', readTime:'٥ دقائق', excerpt:'في دفتر جلدي صغير، كان يكتب ما لا ينتبه إليه أحد...', content:'كان يخرج قبل شروق الشمس بدقائق، يحمل ميكروفونًا صغيرًا ودفترًا جلديًا. لم يكن يبحث عن الموسيقى؛ كان يبحث عن الحياة وهي تحدث من تلقاء نفسها. صوت باب يفتح في الطابق الرابع، ضحكة بائع الخبز، وارتطام أول حافلة بحفرة لم تصلح منذ سنوات. يقول إن المدن لا تتكلم بصوت واحد، وإن مهمته أن يترك لكل صوت مكانًا في الذاكرة.', tags:['مدينة','ذاكرة','حكايات'] },
  { slug:'when-city-breathed', title:'حين أطفأ الحي أنواره، بدأت المدينة تتنفس', category:'قصص قصيرة', categorySlug:'short-stories', date:'الجمعة، ٢٥ سبتمبر ٢٠٢٦', readTime:'٦ دقائق', excerpt:'عن ليلة عادية اكتشف فيها سكان شارع صغير أن الظلام يمكن أن يكون موعدًا للتعارف.', content:'في التاسعة تمامًا انطفأت المصابيح في الشارع كله. خرج الناس من شققهم يحملون هواتفهم، ثم اكتشفوا أن الضوء الأزرق لا يكفي ليُرى الوجه. جلس الجيران على الدرج، وتبادلوا أسماءهم للمرة الأولى. في الصباح عادت الكهرباء، لكن أحدًا لم يعد يغلق بابه باكرًا.', tags:['جيران','ليل','إنسان'] },
  { slug:'why-rain-smells', title:'لماذا نحب رائحة المطر؟', category:'معلومات عامة', categorySlug:'general-knowledge', date:'الثلاثاء، ٢٢ سبتمبر ٢٠٢٦', readTime:'٤ دقائق', excerpt:'العلم خلف الرائحة التي تعيدنا إلى طفولتنا.', content:'الرائحة التي تظهر بعد المطر ليست رائحة الماء وحده. عندما تضرب القطرات التربة، تُطلق زيوتًا نباتية ومركبًا تنتجه بكتيريا دقيقة اسمه جيوسمين. أنوفنا شديدة الحساسية لهذا المركب، وربما لهذا السبب نشعر أن أول مطرة تحمل معها مكانًا قديمًا وذكرى بعيدة.', tags:['طبيعة','علم','مطر'] },
  { slug:'forgotten-library', title:'المكتبة التي نجت من ثلاث مدن', category:'تاريخ', categorySlug:'history', date:'السبت، ١٩ سبتمبر ٢٠٢٦', readTime:'٧ دقائق', excerpt:'رحلة كتاب واحد بين الرفوف والحدود.', content:'لم تكن المكتبة مبنى واحدًا، بل عادةً يحملها الناس معهم. حين انتقلت العائلة من مدينة إلى أخرى، بقيت الصناديق الخشبية مغلقة حتى آخر يوم. في كل مدينة كان كتاب يُضاف، وفي كل رحيل كان كتاب يُترك لصديق. بعد ثلاثة أجيال، صار الرف خريطةً لأماكن لم تعد كما كانت.', tags:['كتب','ذاكرة','مدن'] },
  { slug:'trees-communicate', title:'هل تتحدث الأشجار فعلًا؟', category:'علوم', categorySlug:'science', date:'الأربعاء، ١٦ سبتمبر ٢٠٢٦', readTime:'٥ دقائق', excerpt:'ما نعرفه عن الشبكات الخفية تحت الغابة.', content:'تتبادل الأشجار إشارات كيميائية عبر جذورها والفطريات التي تعيش حولها. لا يعني ذلك أنها تتحدث بلغة بشرية، لكنه يوضح أن الغابة شبكة علاقات لا مجموعة أشجار منفصلة. قد تحذر شجرة جارتها من حشرة، أو ترسل موارد إلى شتلة صغيرة لا تصلها الشمس.', tags:['غابة','بيئة','بحث'] },
  { slug:'small-inventions', title:'اختراعات صغيرة غيّرت صباحنا', category:'تكنولوجيا', categorySlug:'technology', date:'الأحد، ١٣ سبتمبر ٢٠٢٦', readTime:'٦ دقائق', excerpt:'أشياء نستخدمها كل يوم دون أن نعرف الحكاية التي وراءها.', content:'لا تبدأ التكنولوجيا دائمًا في مختبر ضخم. أحيانًا تبدأ بسؤال بسيط: كيف نفتح هذه العلبة بسهولة؟ أو كيف نعرف الوقت دون أن نوقظ أحدًا؟ وراء الأشياء اليومية أفكار كثيرة وتجارب فاشلة، وهذا بالضبط ما يجعلها قريبة من حياتنا.', tags:['اختراع','يوميات','تقنية'] },
  { slug:'the-language-of-tea', title:'الشاي الذي يختار موضوع الحديث', category:'ثقافة', categorySlug:'culture', date:'الخميس، ١٠ سبتمبر ٢٠٢٦', readTime:'٤ دقائق', excerpt:'عن طقس بسيط يترك للضيوف مساحة كي يقولوا ما جاءوا من أجله.', content:'في بعض البيوت لا يُسأل الضيف مباشرةً عن سبب الزيارة. يوضع الشاي أولًا، ويُترك للوقت أن يختار بداية الحديث. الكوب الأول للمجاملة، والثاني للحكاية، أما الثالث فعادةً ما يحمل الحقيقة التي لم يجد أحد طريقةً ألطف لقولها.', tags:['ثقافة','شاي','عادات'] }
];
const categories = { 'short-stories':'قصص قصيرة', 'real-stories':'قصص واقعية', 'general-knowledge':'معلومات عامة', history:'تاريخ', culture:'ثقافة', science:'علوم', technology:'تكنولوجيا' };
const app = document.querySelector('#app');
const escapeHTML = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function articleCard(article, number='') { return `<article class="story-row"><span class="row-number">${number}</span><div><p class="card-kicker">${article.category} · ${article.readTime}</p><h3><a href="/article/${article.slug}">${escapeHTML(article.title)}</a></h3><p>${escapeHTML(article.excerpt)}</p><div class="story-meta"><span>${article.date.replace(/،.*/, '')}</span><span>${article.readTime}</span></div></div></article>`; }
function renderArticle(article) { const related = articles.filter(a => a.slug !== article.slug && a.categorySlug === article.categorySlug).slice(0,2); app.innerHTML = `<section class="content-page"><p class="eyebrow"><span class="eyebrow-line"></span> ${article.category} · ${article.readTime}</p><h1>${escapeHTML(article.title)}</h1><p class="lead">${escapeHTML(article.excerpt)}</p><div class="story-meta"><span>${article.date}</span><span>محتوى أصلي من راوي</span></div><div class="ad-slot" aria-label="مساحة إعلانية"><span>مساحة إعلانية هادئة</span><small>تظهر هنا لاحقًا عند تفعيل الإعلانات</small></div><article><p>${escapeHTML(article.content)}</p><p>كل حكاية تمنحنا طريقة أخرى للنظر. إذا وجدت في هذه القصة ما يستحق المشاركة، أرسلها إلى شخص يحب التفاصيل الصغيرة.</p></article><div class="tags">${article.tags.map(tag => `<span>#${escapeHTML(tag)}</span>`).join(' ')}</div><a class="back-link" href="/">← العودة إلى الأرشيف</a></section>${related.length ? `<section class="content-section"><div class="section-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span> أكمل الرحلة</p><h2>محتوى قريب</h2></div></div><div class="story-list">${related.map((a,i)=>articleCard(a,`0${i+1}`)).join('')}</div></section>` : ''}`; }
function renderCategory(slug) { const name = categories[slug] || 'الأرشيف'; const items = articles.filter(a => a.categorySlug === slug); app.innerHTML = `<section class="content-page"><p class="eyebrow"><span class="eyebrow-line"></span> تصنيف راوي</p><h1>${name}</h1><p class="lead">مساحة من أرشيف راوي لمن يحب أن يتبع هذا الخيط من الفضول.</p><div class="story-list">${(items.length ? items : articles.slice(0,4)).map((a,i)=>articleCard(a,`0${i+1}`)).join('')}</div><a class="back-link" href="/">← العودة إلى الرئيسية</a></section>`; }
function renderStatic(path) { const pages = { '/about':['عن راوي','رفّ عربي صغير يحوّل الفضول إلى حكاية قابلة للمشاركة.','نؤمن أن المحتوى الجيد لا يحتاج إلى ضجيج كي يصل. نكتب القصص والمعلومات من الصفر، نراجعها بعناية، ونترك للقارئ مساحة كي يكوّن رأيه. راوي مشروع عربي يبدأ صغيرًا، لكنه مصمم ليكبر مع كل قارئ وكل كاتب وكل حكاية تستحق مكانًا في الذاكرة.'], '/privacy':['سياسة الخصوصية','خصوصيتك ليست مساحة للإعلان.','نجمع أقل قدر ممكن من البيانات اللازمة لتشغيل الموقع. قد نستخدم ملفات ارتباط أساسية لتحسين التجربة، وقد تظهر لاحقًا خدمات إعلانية تضع ملفاتها وفق سياساتها الخاصة. لن نبيع بياناتك الشخصية، ويمكنك التواصل معنا بشأن أي طلب متعلق بخصوصيتك.'], '/terms':['شروط الاستخدام','استخدم راوي باحترام، واترك القصص أفضل مما وجدتها.','المحتوى المنشور في راوي مخصص للقراءة والمشاركة مع الإشارة إلى المصدر. لا يجوز نسخ المحتوى أو إعادة نشره تجاريًا دون إذن. يحق لنا تحديث المحتوى أو هذه الشروط عند الحاجة، وسنحافظ على وضوح التغييرات.'], '/disclaimer':['إخلاء المسؤولية','المعرفة بداية للحوار وليست بديلًا عن المختص.','المعلومات المنشورة تثقيفية عامة ولا تشكل نصيحة طبية أو قانونية أو مالية. نبذل جهدًا للتحقق من التفاصيل، لكننا نوصي بالرجوع إلى المصادر المتخصصة عند اتخاذ قرارات مهمة. القصص الأدبية تعبير إبداعي وليست وصفًا لوقائع ملزمة.'] }; const page=pages[path]; if(!page) return false; app.innerHTML=`<section class="content-page"><p class="eyebrow"><span class="eyebrow-line"></span> راوي</p><h1>${page[0]}</h1><p class="lead">${page[1]}</p><article><p>${page[2]}</p></article><a class="back-link" href="/">← العودة إلى الرئيسية</a></section>`; return true; }
function route() { const path = window.location.pathname; if (path.startsWith('/article/')) { const item=articles.find(a=>a.slug===path.split('/')[2]); if(item) renderArticle(item); return; } if(path.startsWith('/category/')) { renderCategory(path.split('/')[2]); return; } renderStatic(path); }
route();
document.addEventListener('click', (event) => { const link=event.target.closest('a'); if(!link || !link.href.startsWith(window.location.origin) || link.hash || link.target === '_blank') return; const dest=new URL(link.href); if(dest.pathname.startsWith('/article/') || dest.pathname.startsWith('/category/') || ['/about','/privacy','/terms','/disclaimer'].includes(dest.pathname)) { event.preventDefault(); history.pushState({},'',dest.pathname); route(); window.scrollTo({top:0,behavior:'smooth'}); } });
window.addEventListener('popstate', route);
const overlay=document.querySelector('#search-overlay'); const searchInput=document.querySelector('#search-input'); const results=document.querySelector('#search-results');
function openSearch(){overlay.hidden=false;document.body.style.overflow='hidden';setTimeout(()=>searchInput.focus(),40)} function closeSearch(){overlay.hidden=true;document.body.style.overflow=''}
document.querySelectorAll('[data-open-search]').forEach(btn=>btn.addEventListener('click',openSearch)); document.querySelectorAll('[data-close-search]').forEach(btn=>btn.addEventListener('click',closeSearch)); overlay.addEventListener('click',e=>{if(e.target===overlay)closeSearch()}); document.addEventListener('keydown',e=>{if(e.key==='/' && document.activeElement.tagName!=='INPUT'){e.preventDefault();openSearch()} if(e.key==='Escape')closeSearch()});
searchInput.addEventListener('input',()=>{const query=searchInput.value.trim().toLowerCase(); if(!query){results.innerHTML='<p>ابدأ بكتابة كلمة للبحث في القصص والمعلومات.</p>';return} const matches=articles.filter(a=>[a.title,a.excerpt,a.category,...a.tags].join(' ').toLowerCase().includes(query)); results.innerHTML=matches.length?matches.map(a=>`<a class="search-result" href="/article/${a.slug}"><small>${a.category} · ${a.readTime}</small><strong>${escapeHTML(a.title)}</strong></a>`).join(''):'<p>لم نجد قصة بهذه الكلمات بعد. جرّب كلمة أخرى.</p>'; });
document.querySelector('#newsletter-form')?.addEventListener('submit',e=>{e.preventDefault(); const email=document.querySelector('#email'); const message=document.querySelector('#newsletter-message'); message.textContent=`تم تسجيل ${email.value} — سنرسل لك أول رسالة راوي عند إطلاقها.`; message.style.color='var(--amber-deep)'; e.target.reset();});
